USE sample;
GO
IF (OBJECT_ID ('sample.SECTION_FORMTYPEID_FK', 'F')) IS NOT NULL 
BEGIN
	 ALTER TABLE sample.SECTION
	 DROP CONSTRAINT SECTION_FORMTYPEID_FK;
END;
GO

IF (OBJECT_ID ('sample.SECTION', 'U')) IS NOT NULL 
BEGIN
	 DROP TABLE sample.SECTION;
END;
GO

IF (OBJECT_ID ('sample.vFormType', 'V')) IS NOT NULL 
BEGIN
	 DROP VIEW sample.vFormType;
END;
GO

DROP SCHEMA sample;
GO
