---
name: RefProfile
comment: 'This profile performs actions against the Reference DAO and associated mid-tier objects'
methods:
       - method-name: 'GetAllReferences'
         comment: 'This method gets all references from the data-base'
         return-type: list
         dao-referenced: RefDAO
         input-variables-list: 
             - variable-name: ''
               data-type: ''
         dao-method-name: GetAllRefs
         dao-input-parameters:
            - input-parameter: ''
       - method-name: 'GetReferenceByRefId'
         comment: 'This method gets a specific reference from the data-base by a parameterized reference id'
         return-type: ReferenceVO
         dao-referenced: RefDAO
         input-variables-list: 
             - variable-name: 'refId'
               data-type: 'int'
         dao-method-name: GetRefByRefId
         dao-input-parameters:
            - input-parameter: 'refId'

...