--- #Schema Model:
name: SECTION
fields:
    - field-name: SECTIONID
      data-type: INT
      is-primary-key: True
      auto-increment: True
      length: 0
      is-foreign-key-constraint: False
      foreign-key-name: ''
      foreign-key-table: ''
    - field-name: NAME
      data-type: VARCHAR
      is-primary-key: False
      auto-increment: False
      length: 50
      is-foreign-key-constraint: False
      foreign-key-name: ''
      foreign-key-table: ''
    - field-name: FORMTYPEID
      data-type: INT
      is-primary-key: False
      auto-increment: False
      length: 0
      is-foreign-key-constraint: True
      foreign-key-name: FORMTYPEID
      foreign-key-table: FORMTYPE
---
name: FORMTYPE
fields:
    - field-name: FORMTYPEID
      data-type: INT
      is-primary-key: True
      auto-increment: True
      length: 0
      is-foreign-key-constraint: False
      foreign-key-name: ''
      foreign-key-table: ''
    - field-name: FORMTYPE
      data-type: VARCHAR
      is-primary-key: False
      auto-increment: False
      length: 50
      is-foreign-key-constraint: False
      foreign-key-name: ''
      foreign-key-table: ''
    
...
