--- #View Model - GetTest
name: vFormType
select-clause: 
       - select-field: FORMTYPEID
         table-alias: 
       - select-field: FORMTYPENAME 
         table-alias: 
from-clause: 
       - from-table-name: FORMTYPE
         table-alias:       
where-clause:  
---
name: vSection
select-clause: 
       - select-field: SECTIONID
         table-alias: 
       - select-field: NAME AS SECTIONNAME
         table-alias: 
       - select-field: FORMTYPEID
         table-alias: 
from-clause: 
       - from-table-name: SECTION
         table-alias:       
where-clause:   
---   
name: vSectionFormType
select-clause: 
       - select-field: SECTIONID
         table-alias: SEC
       - select-field: FORMTYPEID
         table-alias: FT
       - select-field: FORMTYPENAME
         table-alias: FT
from-clause: 
       - from-table-name: SECTION
         table-alias: SEC
       - from-table-name: FORMTYPE
         table-alias: FT
      
where-clause: 
       - l-field-name: FORMTYPEID
         l-table-name: SEC
         evaluation: '='
         r-field-name: FORMTYPEID
         r-table-name: FT
...